services:
  workspace:
    build: .
    command: nginx -g 'daemon off;'
    volumes:
      - ..:/workspace
      - home:/root:delegated
    environment:
      DATABASE_URL: postgresql://superuser:password@database/app
      JWT_PRIVATE_KEY: a4b1c6a90d47f6630849db54b97bad77
      PASSWORD_PEPPER: 54418efed47abf0e7cfbc606d097a4dc

  database:
    image: postgres:18
    volumes:
      - database:/var/lib/postgresql
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app

volumes:
  home:
  database: